# Generated by Django 5.1.1 on 2024-12-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
