# Generated by Django 5.1.1 on 2024-12-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_post_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
