# Generated by Django 5.1.1 on 2024-12-20 21:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_post_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(max_length=100)),
                ('info_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('info_image', models.ImageField(default='info/1.jpg', upload_to='info')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
