# Generated by Django 5.1.1 on 2024-12-20 22:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_infomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('about_image', models.ImageField(default='about/about1.jpg', upload_to='about')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('team_image', models.ImageField(default='team/team.jpg', upload_to='team')),
            ],
        ),
    ]
